title: My GitHub Pages Site
description: >- # this means to ignore newlines until "baseurl:"
  Ini adalah deskripsi dari situs GitHub Pages saya.
baseurl: "" # URL dasar (misalnya /blog)
url: "https://username.github.io" # Ganti dengan URL GitHub Pages kamu

# Pilihan tema GitHub Pages
theme: minima

# Konfigurasi lainnya bisa ditambahkan di sini
