title: Roniyansyah
description: >- # this means to ignore newlines until "baseurl:"
  Basinggah Balajar Babarakat
baseurl: "" # URL dasar (misalnya /blog)
url: "https://roniyansyah.github.io" # Ganti dengan URL GitHub Pages kamu

# Pilihan tema GitHub Pages
theme: minima

# Konfigurasi lainnya bisa ditambahkan di sini
